# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anotherGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(584, 368)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(QtCore.QDateTime.currentDateTime(),Form)
        self.dateTimeEdit.setGeometry(QtCore.QRect(190, 90, 194, 22))
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setGeometry(QtCore.QRect(190, 170, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spinBox.setFont(font)
        self.spinBox.setPrefix("")
        self.spinBox.setMaximum(9999)
        self.spinBox.setProperty("value", 50)
        self.spinBox.setObjectName("spinBox")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(400, 250, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(110, 90, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(110, 170, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "确认开机采样时间和频率"))
        self.dateTimeEdit.setDisplayFormat(_translate("Form", "yyyy-MM-dd HH:mm:ss"))
        self.spinBox.setSuffix(_translate("Form", "Hz"))
        self.pushButton.setText(_translate("Form", "确认"))
        self.label.setText(_translate("Form", "日期："))
        self.label_2.setText(_translate("Form", "频率："))
